### PR TITLE
Showing route names implemented, RouteDebugger.RewriteRoutesForTesting used again

### PR DESCRIPTION
**Pull request by ChefIT**
Showing route names implemented, RouteDebugger.RewriteRoutesForTesting used again,
converted for Visual Studio 2013, + .Net 4.51, redesigned for stand-alone using RouteDebug without of RouteMagic

### CODE REVIEW

**Comment by Haacked** [comment]
Hmm, I think you made a mistake. I don't see any of your changes.

**Comment by interTrend** [comment]
Am 13.01.2016 um 05:28 schrieb Phil Haack:
>
> Hmm, I think you made a mistake. I don't see any of your changes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Haacked/RouteMagic/pull/16#issuecomment-171162728>.
>

-- 
interTrend Software GmbH
Mozartstraße 18
68161 Mannheim

Tel.:    06 21 / 15 60 233
Fax:    06 21 / 15 60 235
e-mail: info@intertrend.net <mailto:info@intertrend.net>

Geschäftsführung: Dr.-Ing. Wladimir Drentschew

Amtsgericht Mannheim:   HRB 6977

UstNr DE 181 398 340

**Comment by interTrend** [comment]
What can I do? It looks for me so:

Am 13.01.2016 um 05:28 schrieb Phil Haack:
>
> Hmm, I think you made a mistake. I don't see any of your changes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Haacked/RouteMagic/pull/16#issuecomment-171162728>.
>

-- 
interTrend Software GmbH
Mozartstraße 18
68161 Mannheim

Tel.:    06 21 / 15 60 233
Fax:    06 21 / 15 60 235
e-mail: info@intertrend.net <mailto:info@intertrend.net>

Geschäftsführung: Dr.-Ing. Wladimir Drentschew

Amtsgericht Mannheim:   HRB 6977

UstNr DE 181 398 340

**Comment by Haacked** [comment]
Did you fork my repo?

**Comment by interTrend** [comment]
No, I think I didn't!
You have the screeenshot - I work with "master".




Best regards

Wlady


Am 13.01.2016 um 18:46 schrieb Phil Haack:
>
> Did you fork my repo?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Haacked/RouteMagic/pull/16#issuecomment-171376822>.
>

-- 
interTrend Software GmbH
Mozartstraße 18
68161 Mannheim

Tel.:    06 21 / 15 60 233
Fax:    06 21 / 15 60 235
e-mail: info@intertrend.net <mailto:info@intertrend.net>

Geschäftsführung: Dr.-Ing. Wladimir Drentschew

Amtsgericht Mannheim:   HRB 6977

UstNr DE 181 398 340

**Comment by Haacked** [comment]
Hi @interTrend. I know. You submitted a pull request that is attempting to merge the `master` branch of my repository into the `test` branch of my repository. But you don't have access to change my repository so that's never going to work.

If you're trying to fix something in haacked/routemagic, you need to first fork my repository. Commit your changes in your fork and push them to your fork. Then you can submit a pull request to my repository with your changes.

Does that make sense?

**Comment by Haacked** [comment]
Here's our user documentation for submitting pull requests. https://help.github.com/articles/using-pull-requests/

**Comment by interTrend** [comment]
O.K.

Am 13.01.2016 um 23:39 schrieb Phil Haack:
>
> Hi @interTrend <https://github.com/interTrend>. I know. You submitted 
> a pull request that is attempting to merge the |master| branch of my 
> repository into the |test| branch of my repository. But you don't have 
> access to change my repository so that's never going to work.
>
> If you're trying to fix something in haacked/routemagic, you need to 
> first fork my repository. Commit your changes in your fork and push 
> them to your fork. Then you can submit a pull request to my repository 
> with your changes.
>
> Does that make sense?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Haacked/RouteMagic/pull/16#issuecomment-171459951>.
>

-- 
interTrend Software GmbH
Mozartstraße 18
68161 Mannheim

Tel.:    06 21 / 15 60 233
Fax:    06 21 / 15 60 235
e-mail: info@intertrend.net <mailto:info@intertrend.net>

Geschäftsführung: Dr.-Ing. Wladimir Drentschew

Amtsgericht Mannheim:   HRB 6977

UstNr DE 181 398 340

**Pull request closed without merging**
